name: test sftp
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Setup tmate session
       uses: mxschmitt/action-tmate@v1      
#     - name: Deploy
#        run: |
#         touch test.txt
#         sftp -q -i private_key -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P $PORT $USER@$HOST:/ <<< $'put -rp test.txt'
